<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Ordering.Application/Ordering.Application.csproj" />
    <ProjectReference Include="../Ordering.Domain/Ordering.Domain.csproj" />
    <ProjectReference Include="../../../Contracts/Catalog.Grpc/Catalog.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <PropertyGroup>
    <BuildInParallel>false</BuildInParallel>
  </PropertyGroup>

</Project>
