<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Services/Ordering/Ordering.Domain/Ordering.Domain.csproj" />
    <ProjectReference Include="../../src/Services/Ordering/Ordering.Application/Ordering.Application.csproj" />
    <ProjectReference Include="../../src/Services/Ordering/Ordering.Infrastructure/Ordering.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Contracts/IntegrationEvents/IntegrationEvents.csproj" />
    <ProjectReference Include="../../src/BuildingBlocks/EventBus/EventBus.csproj" />
    <ProjectReference Include="../../src/BuildingBlocks/Exceptions/Exceptions.csproj" />
  </ItemGroup>

</Project>
