<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Ordering.Domain/Ordering.Domain.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/EventBus/EventBus.csproj" />
    <ProjectReference Include="../../../Contracts/IntegrationEvents/IntegrationEvents.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stripe.net" />
    <PackageReference Include="PayPalCheckoutSdk" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
